model_list:
  - model_name: my-model
    litellm_params:
      model: openai/accounts/fireworks/routers/kimi-k2p5-turbo
      api_base: os.environ/API_BASE_URL
      api_key: os.environ/LLM_API_KEY
      rpm: 1000
      tpm: 60000
      input_cost_per_token: 0.0000006
      output_cost_per_token: 0.0000035

litellm_settings:
  drop_params: true
  success_callback: ["db"]
  failure_callback: ["db"]

general_settings:
  master_key: os.environ/MASTER_KEY
  database_url: os.environ/DATABASE_URL
  control_plane_url: os.environ/CONTROL_PLANE_URL
  store_model_in_db: true
  store_prompts_in_spend_logs: true
  port: 4000
  host: 0.0.0.0

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 3
  timeout: 60